### ISSUE TITLE
HTTP error: 500 Internal Server Error

### ISSUE THREAD

**Issue by band-rk** [BartekSz95/phpvirtualbox#6]
Error 500 appeared after installation before login
![1](https://user-images.githubusercontent.com/94367173/212061057-37ee8e88-80da-4960-ab1c-f768fdfd48cf.png)

**Comment by BartekSz95** [comment]
Something wrong is with your VirtualBox installation, not with phpVirtualBox.

Please, read wiki:

**Comment by band-rk** [comment]
The virtualbox work properly. Fiv VMs are work. vboxweb package was install, configure and running. phpvirtualbox ver 5.2 was installed for the purpose of testing  (worked! but work incorrect). After installing phpvirtualbox ver 7.0 the error abowe was apper.

**Comment by BartekSz95** [comment]
I'm using this version of phpVirtualBox with VBox 7.0 on my dedi. You don't post details,  so what can I know what you have wrong on your configs? This isn't problem with phpVirtualBox, but with configs or server settings.

**Comment by dirk-cgn** [comment]
I had the same issue as @band-rk, so I looked in the error log:

PHP Fatal error:  Uncaught TypeError: Return value of VBox_Collection::current() must be an instance of mixed, instance of IGuestOSType returned in /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php:156\nStack trace:\n#0 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php(173): VBox_Collection->current()\n#1 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxconnector.php(3170): VBox_Collection->valid()\n#2 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxconnector.php(952): vboxconnector->remote_vboxGetGuestOSTypes()\n#3 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/api.php(316): vboxconnector->__call()\n#4 {main}\n  thrown in /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php on line 156

I tried fixing it by changing line 156 in phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php: 

```php
    #[\ReturnTypeWillChange]
    public function current()
    {
        return current($this->_objects);
    }
```

Previous this method returned : mixed, but this didn't work with my PHP 7.4. Using this change phpVirtualBox works with VBox 7.0(.4) on my Debian machine.

**Comment by BartekSz95** [comment]
> I had the same issue as @band-rk, so I looked in the error log:
> 
> PHP Fatal error:  Uncaught TypeError: Return value of VBox_Collection::current() must be an instance of mixed, instance of IGuestOSType returned in /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php:156\nStack trace:\n#0 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php(173): VBox_Collection->current()\n#1 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxconnector.php(3170): VBox_Collection->valid()\n#2 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxconnector.php(952): vboxconnector->remote_vboxGetGuestOSTypes()\n#3 /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/api.php(316): vboxconnector->__call()\n#4 {main}\n  thrown in /opt/vbox/phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php on line 156
> 
> I tried fixing it by changing line 156 in phpvirtualbox-7.0-rc1/endpoints/lib/vboxServiceWrappers.php: 
> 
> ```php
>     #[\ReturnTypeWillChange]
>     public function current()
>     {
>         return current($this->_objects);
>     }
> ```
> 
> Previous this method returned : mixed, but this didn't work with my PHP 7.4. Using this change phpVirtualBox works with VBox 7.0(.4) on my Debian machine.
> 
> Hope this helps.

I can't remove this line, because it break compatibility with PHP8.

My version is for PHP8.0, 8.1 and 8.2. I can't support 7.4, because PHP authors changed a lot into PHP8. Problem is with PHP7.4 which is officially unsupported by developers.

There is a list of supported PHP versions: https://www.php.net/supported-versions.php

Sorry, but I can't create phpVirtualBox for every PHP versions. Only way is upgrade PHP to 8.1 or 8.2. If your server is based on Debian or Ubuntu, you can use this packages for PHP8.2: https://deb.sury.org/

There is tutorial: https://php.watch/articles/install-php82-ubuntu-debian

**Comment by dirk-cgn** [comment]
@BartekSz95 thanks for the extensive comment and the links to the PHP versions. I've not coded in PHP for a few years now, and I am really behind the current versions, so that is very helpful. I found your fork when looking for a version of phpvirtualbox running with Vbox 7, and unfortunately I didn't see any notice that it is for PHP 8.0+ only. Anyway, I got it to work for me thanks to your repo, so many thanks for that! And maybe my hint will help others which are trying to get it to run with an older version of PHP. I can completely understand that you're only supporting current versions. 

So thanks for the repo and your good work!

**Comment by BartekSz95** [comment]
@dirk-cgn Yes, I need to put information about supporting PHP versions to README.md file. I glad that everything works after PHP update to current versions 🙂
